# Generated by Django 3.0.4 on 2020-05-31 04:53

import datetime
from django.db import migrations, models
import django.db.models.deletion
import my_financial_app.enums


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=200)),
                ('owner_surname', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='CashAccMonth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beginning_calendar_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='MoneyTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True)),
                ('created_date', models.DateTimeField(default=datetime.datetime.now)),
                ('amount', models.IntegerField()),
                ('number_of_installments', models.IntegerField(null=True)),
                ('total_number_of_installments', models.IntegerField(null=True)),
                ('transaction_type', models.CharField(choices=[(my_financial_app.enums.TransactionType['CASHIN'], 'CASHIN'), (my_financial_app.enums.TransactionType['CASHOUT'], 'CASHOUT')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CardMonth',
            fields=[
                ('cashaccmonth_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='my_financial_app.CashAccMonth')),
                ('closing_credit_card_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
            bases=('my_financial_app.cashaccmonth',),
        ),
        migrations.CreateModel(
            name='CashAccount',
            fields=[
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='my_financial_app.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=30)),
                ('bank', models.CharField(max_length=40)),
                ('card_type', models.CharField(choices=[(my_financial_app.enums.CardType['MASTERCARD'], 'MASTERCARD'), (my_financial_app.enums.CardType['VISA'], 'VISA'), (my_financial_app.enums.CardType['AMEX'], 'AMEX')], max_length=200)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_financial_app.Account')),
            ],
        ),
    ]
