# Generated by Django 3.0.4 on 2020-05-31 22:44

from django.db import migrations, models
import django.db.models.deletion
import my_financial_app.enums


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=200)),
                ('owner_surname', models.CharField(max_length=200)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=30)),
                ('bank', models.CharField(max_length=40)),
                ('card_type', models.CharField(choices=[(my_financial_app.enums.CardType['MASTERCARD'], 'MASTERCARD'), (my_financial_app.enums.CardType['VISA'], 'VISA'), (my_financial_app.enums.CardType['AMEX'], 'AMEX')], max_length=200)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_financial_app.Account')),
            ],
        ),
        migrations.CreateModel(
            name='MoneyTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('category', models.CharField(choices=[(my_financial_app.enums.TransactionCategory['LEISURE'], 'LEISURE'), (my_financial_app.enums.TransactionCategory['FOOD'], 'FOOD'), (my_financial_app.enums.TransactionCategory['INVESTMENT'], 'INVESTMENT'), (my_financial_app.enums.TransactionCategory['SAVING'], 'SAVING'), (my_financial_app.enums.TransactionCategory['SERVICES'], 'SERVICES'), (my_financial_app.enums.TransactionCategory['RENT'], 'RENT'), (my_financial_app.enums.TransactionCategory['GROCERIES'], 'GROCERIES')], max_length=200)),
                ('amount', models.IntegerField()),
                ('number_of_installments', models.IntegerField(default=1)),
                ('total_number_of_installments', models.IntegerField(default=1)),
                ('transaction_type', models.CharField(choices=[(my_financial_app.enums.TransactionType['CASHIN'], 'CASHIN'), (my_financial_app.enums.TransactionType['CASHOUT'], 'CASHOUT')], max_length=200)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_financial_app.Card')),
            ],
        ),
    ]
