# Generated by Django 3.0.4 on 2020-03-31 18:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("my_financial_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="created_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="todo",
            name="description",
            field=models.TextField(null=True),
        ),
    ]
